name: Deploy to Firebase Hosting

on:
  push:
    branches: main
      - main  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the version you need

      - name: Install dependencies
        run: |
          npm install -g firebase-tools
          npm install  # If you have a package.json

      - name: Deploy to Firebase Hosting
        run: |
          firebase use --add  # Make sure this selects the correct Firebase project
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
